[package]
name = "hass-alexa-relay"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
clap = { version = "4.4.10", features = ["derive", "env"] }
lambda_runtime = "0.8.1"
log = "0.4.19"
onetun = { version = "0.3.4", default-features = false }
pretty_env_logger = "0.5.0"
reqwest = { version = "0.11.18", features = ["rustls-tls-native-roots"], default-features = false }
serde = { version = "1.0.163", features = ["serde_derive"] }
serde_json = "1.0.104"
tokio = { version = "1.33.0", features = ["tokio-macros"] }
