[package]
name = "hass-alexa-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
clap = { version = "3.2.22", features = ["derive", "env"] }
lambda_runtime = "0.7.3"
log = "0.4.17"
onetun = { version = "0.3.4", default-features = false }
pretty_env_logger = "0.4.0"
reqwest = { version = "0.11.16", features = ["rustls-tls-native-roots"], default-features = false }
serde = { version = "1.0.159", features = ["serde_derive"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["tokio-macros"] }
